#!/bin/bash

commit_regex='^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .+'
error_msg="ERROR: Commit message does not follow the Conventional Commits format."

# Prevent empty commit messages.
if [ -z "$(cat "$1" | awk '{$1=$1};1')" ]; then
  echo "ERROR: Empty commit message, please provide a commit message." >&2
  exit 1
fi

# Check commit message format.
if ! grep -iqE "$commit_regex" "$1"; then
  echo "$error_msg" >&2
  exit 1
fi

# Check if the commit message is too long.
if [ "$(cat "$1" | wc -l)" -ne 1 ] || [ "$(cat "$1" | wc -c)" -gt 51 ]; then
  echo "ERROR: Commit message is too long (should be <= 50 chars in a single line)." >&2
  exit 1
fi
