# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do |lane, options|
    app_store_connect_api_key(
      key_id: '4H27D3QLG2',
      issuer_id: 'ec2c19af-8deb-4579-be01-5d677995d709',
      key_filepath: './AuthKey.p8'
    )
    setup_ci if ENV['CI']
  end

  lane :versioning do
    tag = last_git_tag(pattern: 'v[0-9].*')
    increment_version_number(
    version_number: tag[1..-1] # Set a specific version number
    )
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: 'Runner.xcodeproj'
    )
  end

  lane :integration do
    match(type: 'appstore', readonly: is_ci)
    build_ios_app(
        export_method: 'app-store',
        output_name: 'Runner-development'
    )
  end

  lane :beta do
    match(type: 'appstore', readonly: is_ci)
    build_ios_app(
        export_method: 'app-store',
    )
  end

  lane :upload do
    upload_to_app_store(
        skip_waiting_for_build_processing: true,
    )
  end

  lane :register do
    register_devices(devices_file: './fastlane/devices.txt')
    match(readonly: false)
    match(type: 'development', force_for_new_devices: true, readonly: false)
  end
end
