name: conventional-release
on:
 workflow_call:
   outputs:
     new_release_published:
      description: 'If a new release was published'
      value: ${{ jobs.conventional-release.outputs.new_release_published }}

jobs:
  conventional-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set output
        id: output
        run: echo new_release_published=${{ steps.semantic.outputs.new_release_published }} >> $GITHUB_OUTPUT

    outputs:
        new_release_published: ${{ steps.output.outputs.new_release_published }}
