name: conventional-release
on:
 workflow_call:
   outputs:
     new_release_published: ${{ jobs.conventional-release.outputs.new_release_published }}

jobs:
  conventional-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set output
        id: output
        run: echo new_release_published=${{ steps.semantic.outputs.new_release_published }} >> $GITHUB_OUTPUT

    outputs:
        new_release_published: ${{ steps.output.outputs.new_release_published }}
