name: integration-screenshot
on:
  workflow_call:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: ios
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      - run: flutter build ios --simulator --target=integration_test/screenshot_test.dart
      - run: flutter build apk --debug --target=integration_test/screenshot_test.dart
      - name: Archive integration ipa
        uses: actions/upload-artifact@v3
        with:
          name: app-simulator-build
          path: build/ios/iphonesimulator/Runner.app
          if-no-files-found: error
          retention-days: 3

      - name: Archive integration apk
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error
          retention-days: 3

  take-screenshot-ios:
    if: false
    runs-on: macos-latest
    needs:
      - build
    timeout-minutes: 15
    strategy:
      matrix:
        #model: ['iPhone 13 Pro Max', 'iPhone 8', 'iPad Pro (12.9-inch) (5th generation)', 'iPad Pro (11-inch) (3rd generation)']
        model: ['iPhone SE (3rd generation)']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download app
        uses: actions/download-artifact@v3
        with:
          name: app-simulator-build
          path: build/ios/iphonesimulator/Runner.app

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      - uses: futureware-tech/simulator-action@v2
        with:
          model: ${{ matrix.model }}
      - run: >-
          flutter drive
          --driver=test_driver/screenshot_test.dart
          --use-application-binary=build/ios/iphonesimulator/Runner.app

      - name: Append model name to all files in screenshots folder
        run: |
          for file in screenshots/*; do
            filename=$(basename "$file")
            mv "$file" "screenshots/${{ matrix.model }}-$filename"
          done

      - name: Archive screenshots
        uses: actions/upload-artifact@v3
        with:
          name: ios-screenshot-${{ matrix.model }}
          path: screenshots
          if-no-files-found: error
          retention-days: 7
  take-screenshot-android:
    runs-on: macos-latest
    needs:
      - build
    timeout-minutes: 15
    env:
      API_LEVEL: 29
      CORES: 3
    strategy:
      matrix:
        model: ['pixel_6']
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Download app
        uses: actions/download-artifact@v3
        with:
          name: app-debug.apk

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.API_LEVEL }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          profile: ${{ matrix.model }}
          target: google_apis
          cores: ${{ env.CORES }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: avdmanager list device

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          profile: ${{ matrix.model }}
          target: google_apis
          cores: ${{ env.CORES }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: "flutter drive --driver=test_driver/screenshot_test.dart --use-application-binary=app-debug.apk"

      - name: Append model name to all files in screenshots folder
        run: |
          for file in screenshots/*; do
            filename=$(basename "$file")
            mv "$file" "screenshots/${{ matrix.model }}-$filename"
          done


      - name: Archive screenshots
        uses: actions/upload-artifact@v3
        with:
          name: android-screenshot-${{ matrix.model }}
          path: screenshots
          if-no-files-found: error
          retention-days: 7

  commit-screenhots:
    runs-on: ubuntu-latest
    needs:
      - take-screenshot-android
 #     - take-screenshot-ios
    timeout-minutes: 5
    strategy:
      matrix:
        locale: [ 'en-US' ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          path: screenshots

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: screenshots

      - name: Move ios screenshots
        run: |
          mkdir -p ios/fastlane/screenshots/${{ matrix.locale }}
          find ./screenshots -type f -path '*/ios-*/*' -exec cp {} ios/fastlane/screenshots/${{ matrix.locale }} \;

      - name: Move android screenshots
        run: |
          mkdir -p android/fastlane/metadata/android/${{ matrix.locale }}/images/phoneScreenshots
          find ./screenshots -type f -path '*/android-*/*' -exec cp {} android/fastlane/metadata/android/${{ matrix.locale }}/images/phoneScreenshots \;

      - name: Commit screenshots
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add ios/fastlane/screenshots/${{ matrix.locale }} android/fastlane/metadata/android/${{ matrix.locale }}/images/phoneScreenshots
          git commit -m "chore: Update screenshots" -m  "[skip ci]"
          git push