name: build-android
on:
  workflow_call:
    inputs:
      screenshot:
        type: string
        required: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
          working-directory: android
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      - run: flutter build apk --debug --target=integration_test/screenshot_test.dart
        if: ${{ github.event.inputs.screenshot == 'true' }}

      - name: Archive integration test apk
        if: ${{ github.event.inputs.screenshot == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error
          retention-days: 3

      # Build android Release
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
          working-directory: android

      - run: bundle install

      - run: bundle exec fastlane versioning

      - run: flutter build appbundle --build-number ${{ env.ANDROID_VERSION_CODE }} --build-name ${{ env.ANDROID_VERSION_NAME }} --target lib/main.dart

      - name: Archive appbundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error
          retention-days: 3