name: build-release-ios
on:
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "beta"
        type: choice
        options:
          - beta
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: ios
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      # Change the following key to match your secret repository choice
      - run: 'echo "$GC_KEYS" > gc_keys.json'
        shell: bash
        env:
          GC_KEYS: ${{secrets.GC_KEYS }}
      - run: 'echo "$API_KEY" > AuthKey.p8'
        shell: bash
        env:
          API_KEY: ${{secrets.APP_STORE_CONNECT_API_KEY }}
      - run: bundle install
      - run: bundle exec fastlane versioning
      - run: flutter build ios --release --config-only --no-codesign --target=lib/main.dart
      - run: bundle exec fastlane versioning
      - run: bundle exec fastlane ${{ github.event.inputs.lane || 'beta' }}
      - run: bundle exec fastlane upload