name: parse-screenshot

on:
  workflow_call:
    inputs:
      screenshot-text:
        description: 'Text to search for in commit message'
        required: true
        type: string
    outputs:
      contains_screenshot:
        description: 'If commit message contains screenshot keyword'
        value: ${{ jobs.check_commit_message.outputs.contains_screenshot }}

jobs:
  check_commit_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Commit Message for '${{ inputs.screenshot-text }}'
        id: check_commit
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          if [[ $COMMIT_MESSAGE == *"${{ inputs.screenshot-text }}"* ]]; then
            echo "Contains Screenshot: true"
            echo "contains_screenshot=true" >> $GITHUB_OUTPUT
          else
            echo "Contains Screenshot: false"
            echo "contains_screenshot=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

    outputs:
      contains_screenshot: ${{ steps.check_commit.outputs.contains_screenshot }}
