name: integration-screenshot-commit-android
on:
  workflow_call:
    inputs:
      locale:
        required: true
        type: string
    secrets:
      token:
          required: true

jobs:
  commit-screenshots:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        locale: ${{ fromJson(inputs.locale) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          path: screenshots

      - name: Move android screenshots
        run: |
          mkdir -p android/fastlane/metadata/android/${{ matrix.locale }}/images/phoneScreenshots
          find ./screenshots -type f -path '*/android-*/*' -exec cp {} android/fastlane/metadata/android/${{ matrix.locale }}/images/phoneScreenshots \;

      - name: Check for changes in android/fastlane/metadata/android/${{ matrix.locale }}/images/phoneScreenshots
        id: git-diff
        run: |
          git diff --quiet -- 'android/fastlane/metadata/android/${{ matrix.locale }}/images/phoneScreenshots' || (echo "Changes exist in android screenshots" && echo changes=true >> $GITHUB_OUTPUT)
        continue-on-error: true

      - name: Commit screenshots
        if: steps.git-diff.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git config pull.rebase true 
          git add android/fastlane/metadata/android/${{ matrix.locale }}/images/phoneScreenshots
          git commit -m "chore: Update screenshots android" -m  "[skip ci]"
          git pull && git push