name: upload-release-ios
on:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: ios
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download app
        uses: actions/download-artifact@v3
        with:
          name: app-release
          path: ios/Runner.ipa

      - run: 'echo "$API_KEY" > AuthKey.p8'
        shell: bash
        env:
          API_KEY: ${{secrets.APP_STORE_CONNECT_API_KEY }}

      - run: bundle install

      - run: bundle exec fastlane upload_testflight
      - run: bundle exec fastlane upload_metadata_app_store