name: main-pull-request
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  test-analyze:
    uses: ./.github/workflows/01-test-analyze.yml
  lint-pr:
    uses: ./.github/workflows/21-lint-pr.yml