name: Generate Changelog

on:
  workflow_run:
    workflows: ["Conventional Release"]
    branches: [main]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install conventional-changelog-cli
        run: npm install -g conventional-changelog-cli

      - name: Generate Changelog
        run: conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Commit Changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git diff-index --quiet HEAD || git commit -m "chore: update CHANGELOG.md" -m "[skip ci]" && git push
